# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do

  desc "Build para Personal Team (debug/device)"
  lane :build_personal do
    UI.user_error!("Defina PERSONAL_TEAM_ID no ambiente") if ENV["PERSONAL_TEAM_ID"].to_s.strip.empty?

    # Garante que o Xcode usa automatic signing
    update_code_signing_settings(
      use_automatic_signing: true,
      team_id: ENV["PERSONAL_TEAM_ID"], # ex: "A1B2C3D4E5"
      path: "BitrisePOC.xcodeproj"
    )

    gym(
      workspace: "BitrisePOC.xcworkspace",
      scheme: "BitrisePOC",
      configuration: "Debug",
      clean: true,
      codesigning_identity: "Apple Development",
      export_method: "development",
      export_team_id: ENV["PERSONAL_TEAM_ID"],
      xcargs: "-allowProvisioningUpdates -allowProvisioningDeviceRegistration CODE_SIGN_STYLE=Automatic DEVELOPMENT_TEAM=#{ENV['PERSONAL_TEAM_ID']} CODE_SIGN_IDENTITY='Apple Development'",
      export_options: {
        method: "development",
        signingStyle: "automatic",
        teamID: ENV["PERSONAL_TEAM_ID"],
        compileBitcode: false
      },
      skip_archive: false,
      output_directory: "./build",
      output_name: "BitrisePOC-debug.ipa"
    )
  end

end