# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do

  desc "Build para Personal Team (debug/device)"
  lane :build_personal do
    # Garante que o Xcode usa automatic signing
    update_code_signing_settings(
      use_automatic_signing: true,
      team_id: ENV["PERSONAL_TEAM_ID"], # ex: "A1B2C3D4E5"
      path: "ios/BitrisePOC.xcodeproj"
    )

    gym(
      workspace: "ios/BitrisePOC.xcworkspace",
      scheme: "BitrisePOC",
      configuration: "Debug",
      export_method: "development",
      skip_archive: false,
      output_directory: "./build",
      output_name: "BitrisePOC-debug.ipa"
    )
  end

end